server:
  port: 18082

spring:
  application:
    name: rpc-agent1
  mvc:
    async:
      request-timeout: 120s

lrpc:
  provider:
    port: 19082
  agent:
    enabled: true
    registry-base-url: http://localhost:18080
    discovery-base-url: http://localhost:18081

dashscope:
  api-key: ${API_KEY_DASH_SCOPE}
  chat-model: qwen-plus
  timeout-seconds: 120
